-- Delete all correlations that were created before LLM validation was active.
-- These have NULL reasoning because they were generated by keyword-only matching.
DELETE FROM correlations WHERE reasoning IS NULL;
